### ISSUE TITLE
Getting "Error: write after end" on every other log file that is ingested from s3 

### ISSUE THREAD

**Issue by ghost** [awslabs/amazon-elasticsearch-lambda-samples#4]
Thank you for writing this. It's exactly what I needed. However, I'm running into an error with every other log file that is ingested from s3. This is the error as written to the CloudWatch logs:

2015-11-24T19:04:06.486Z    fe5810ee-92dd-11e5-8a9f-8909a00ad51d    Error: write after end 
at writeAfterEnd (_stream_writable.js:133:12) 
at LineStream.Writable.write (_stream_writable.js:181:5) 
at write (_stream_readable.js:602:24) 
at flow (_stream_readable.js:611:7) 
at PassThrough.pipeOnReadable (_stream_readable.js:643:5)
at PassThrough.emit (events.js:92:17) 
at emitReadable_ (_stream_readable.js:427:10) 
at emitReadable (_stream_readable.js:423:5) 
at readableAddChunk (_stream_readable.js:166:9) 
at PassThrough.Readable.push (_stream_readable.js:128:10)

Does the NodeHttpClient need to close it's session or something?

**Comment by srisub-amzn** [comment]
There is a pull request from @picwelltimjones with a fix for the same symptom. Could you see if that works for you?
