### ISSUE TITLE
Unable to import module es

### ISSUE THREAD

**Issue by Nash897** [awslabs/amazon-elasticsearch-lambda-samples#9]
My name of the handler on console is es.handler.
With S3-Lambda-ES I am getting the following error

START RequestId: d6b5b2d1-672d-11e6-a9ef-1dccc79021cb Version: $LATEST 
**Unable to import module 'ES':** Error at Function.Module._resolveFilename (module.js:325:15) at Function.Module._load (module.js:276:25) at Module.require (module.js:353:17) at require (internal/module.js:12:17) at Object.<anonymous> (/var/task/ES.js:19:18) at Module._compile (module.js:409:26) at Object.Module._extensions..js (module.js:416:10) at Module.load (module.js:343:32) at Function.Module._load (module.js:300:12) at Module.require (module.js:353:17)

I am clueless, any inputs will be appreciated.

**Comment by jkpindahbc** [comment]
Still an error, too bad they actually don't try this stuff out.  Kind of kills the desire to learn when the samples don't actually work....

**Comment by jkpindahbc** [comment]
After researching this further it appears that Lambda ignores the package.json file entry point declaration.  The file with the entry point defined in the Lambda Configuration tab needs to be named index.js.  So rename the s3_lambda_es.js to index.js and update the name in entry point of the package.json to index.js.

![image](https://cloud.githubusercontent.com/assets/399519/22798041/5fdee11c-eeb5-11e6-9796-6d4615e96b33.png)

![image](https://cloud.githubusercontent.com/assets/399519/22798077/87a90416-eeb5-11e6-858e-c21a13135a41.png)
